name: Binary build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
          file-path: kmeans
          commit-msg: Update binary through Github Actions CI
          github-token: ${{ secrets.GITHUB_TOKEN }}
